function export_to_cmsis(A, B, filename_base)
    % 1. Sprawdzenie wymiarów
    [rows, cols] = size(A);
    if rows ~= cols
        error('Macierz A musi byc kwadratowa');
    end
    n = rows;
    
    % 2. Obliczenie wyniku referencyjnego w MATLAB
    Ref = A * B;
    
    % 3. Przygotowanie danych (transpozycja dla row-major)
    A_T = A'; 
    A_flat = A_T(:);
    
    %% GENEROWANIE PLIKU .H
    header_file = [filename_base '.h'];
    fh = fopen(header_file, 'w');
    
    fprintf(fh, '/* Auto-generated by MATLAB */\n');
    fprintf(fh, '#ifndef DSP_DATA_H\n');
    fprintf(fh, '#define DSP_DATA_H\n\n');
    fprintf(fh, '#include "arm_math.h"\n\n');
    fprintf(fh, '#define MATRIX_N %d\n\n', n);
    fprintf(fh, 'extern float32_t input_matrix_A[%d];\n', n*n);
    fprintf(fh, 'extern float32_t input_vector_B[%d];\n', n);
    fprintf(fh, 'extern float32_t ref_result[%d];\n', n);
    fprintf(fh, '\n#endif // DSP_DATA_H\n');
    fclose(fh);
    
    %% GENEROWANIE PLIKU .C
    source_file = [filename_base '.c'];
    fc = fopen(source_file, 'w');
    
    fprintf(fc, '/* Auto-generated by MATLAB */\n');
    fprintf(fc, '#include "%s"\n\n', header_file);
    
    % Macierz A
    fprintf(fc, 'float32_t input_matrix_A[%d] = {\n', n*n);
    for i = 1:length(A_flat)
        fprintf(fc, '    %10.5ff', A_flat(i));
        if i < length(A_flat), fprintf(fc, ','); end
        if mod(i, n) == 0, fprintf(fc, '\n'); end
    end
    fprintf(fc, '};\n\n');
    
    % Wektor B
    fprintf(fc, 'float32_t input_vector_B[%d] = {\n', n);
    for i = 1:length(B)
        fprintf(fc, '    %10.5ff', B(i));
        if i < length(B), fprintf(fc, ',\n'); else fprintf(fc, '\n'); end
    end
    fprintf(fc, '};\n\n');
    
    % Wynik referencyjny
    fprintf(fc, 'float32_t ref_result[%d] = {\n', n);
    for i = 1:length(Ref)
        fprintf(fc, '    %10.5ff', Ref(i));
        if i < length(Ref), fprintf(fc, ',\n'); else fprintf(fc, '\n'); end
    end
    fprintf(fc, '};\n');
    fclose(fc);
    
    fprintf('Wygenerowano pliki lokalnie: %s, %s\n', source_file, header_file);

    %% --- PRZENOSZENIE PLIKÓW DO FOLDERÓW PROJEKTU ---
    
    % Definicja ścieżek docelowych (względem folderu skryptu MATLAB)
    srcDest = '../Components/Src';
    incDest = '../Components/Inc';

    % Zabezpieczenie: Utwórz foldery, jeśli nie istnieją
    if ~exist(srcDest, 'dir')
        mkdir(srcDest);
        fprintf('Utworzono folder: %s\n', srcDest);
    end
    if ~exist(incDest, 'dir')
        mkdir(incDest);
        fprintf('Utworzono folder: %s\n', incDest);
    end

    % 1. Przenoszenie pliku .C
    try
        movefile(source_file, fullfile(srcDest, source_file));
        fprintf('PRZENIESIONO: %s -> %s\n', source_file, srcDest);
    catch ME
        warning('Nie udało się przenieść pliku .c: %s', ME.message);
    end

    % 2. Przenoszenie pliku .H
    try
        movefile(header_file, fullfile(incDest, header_file));
        fprintf('PRZENIESIONO: %s -> %s\n', header_file, incDest);
    catch ME
        warning('Nie udało się przenieść pliku .h: %s', ME.message);
    end
    
    % 3. Przenoszenie CSV (jeśli jakieś istnieją - zgodnie z Twoim kodem)
    csvFiles = dir('*.csv');
    if ~isempty(csvFiles)
        for i = 1:length(csvFiles)
            movefile(csvFiles(i).name, fullfile(srcDest, csvFiles(i).name));
            fprintf('PRZENIESIONO: %s -> %s\n', csvFiles(i).name, srcDest);
        end
    end
end